default_settings: null
behaviors:
  FishSF:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  food_cluster:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8263
          value: 0.5
      name: Lesson0
      completion_criteria:
        behavior: FishFoodCollector
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 6.0
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8264
          value: 0.4
      name: Lesson1
      completion_criteria:
        behavior: FishFoodCollector
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 7.0
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8265
          value: 0.3
      name: Lesson2
      completion_criteria:
        behavior: FishFoodCollector
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 8.0
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8266
          value: 0.2
      name: Lesson2
      completion_criteria:
        behavior: FishFoodCollector
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 10.0
        require_reset: true
checkpoint_settings:
  run_id: sfnb0.25fe5f300foodcountnbvisible
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
